# Put this file in: .github/workflows/sync-dictionary.yml

name: Sync Ichrolic Dictionary

on:
  # Trigger when dictionary.json changes
  push:
    paths: 
      - 'dictionary.json'
  
  # Also run twice daily to catch any manual changes
  schedule:
    - cron: '0 6,18 * * *'  # 6 AM and 6 PM UTC
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-dictionary:
    runs-on: ubuntu-latest
    
    # Give the workflow permission to write to the repo
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract and format dictionary
        run: |
          # Extract dictionary and synonyms
          echo "Extracting dictionary and synonyms from JSON..."
          cat dictionary.json | jq '.dictionary' > temp_dict.json
          cat dictionary.json | jq '.synonyms' > temp_synonyms.json
          
          # Count entries for logging
          DICT_COUNT=$(cat temp_dict.json | jq 'length')
          SYN_COUNT=$(cat temp_synonyms.json | jq 'length')
          echo "Found $DICT_COUNT dictionary entries and $SYN_COUNT synonyms"
          
          # Create formatted markdown for Claude
          echo "# Ichrolic Dictionary" > formatted_dictionary.md
          echo "" >> formatted_dictionary.md
          echo "Auto-generated from dictionary.json on $(date)" >> formatted_dictionary.md
          echo "" >> formatted_dictionary.md
          echo "## Translations ($DICT_COUNT main entries + $SYN_COUNT synonyms)" >> formatted_dictionary.md
          echo "" >> formatted_dictionary.md
          
          # Process main dictionary entries with variant handling
          echo "Processing main dictionary entries..." >&2
          cat temp_dict.json | jq -r 'to_entries[] | "\(.key)|\(.value)"' | while IFS='|' read -r key value; do
            if [[ "$key" == *"/"* ]]; then
              # Extract base word and variant type
              base_word=$(echo "$key" | cut -d'/' -f1)
              variant_type=$(echo "$key" | cut -d'/' -f2)
              echo "- **${base_word}** <small style=\"color:#666;\">(${variant_type})</small> → ${value}"
            else
              echo "- **${key}** → ${value}"
            fi
          done | sort >> formatted_dictionary.md
          
          # Add synonyms section if there are any
          if [ "$SYN_COUNT" -gt 0 ]; then
            echo "" >> formatted_dictionary.md
            echo "### Synonyms" >> formatted_dictionary.md
            echo "" >> formatted_dictionary.md
            
            echo "Processing synonyms..." >&2
            # For each synonym, find its canonical form and translation
            cat temp_synonyms.json | jq -r 'to_entries[] | "\(.key)|\(.value)"' | while IFS='|' read -r syn_key syn_value; do
              # Look up the translation for the canonical form
              translation=$(cat temp_dict.json | jq -r --arg key "$syn_value" '.[$key] // "NOT_FOUND"')
              if [ "$translation" != "NOT_FOUND" ]; then
                echo "- **${syn_key}** ~ <small style=\"color:#666;\">*${syn_value}*</small> → ${translation}"
              fi
            done | sort >> formatted_dictionary.md
          fi
          
          echo "Generated markdown file with $DICT_COUNT main entries and $SYN_COUNT synonyms"
      
      - name: Upload dictionary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ichrolic-dictionary
          path: formatted_dictionary.md
          retention-days: 30
      
      - name: Commit processed dictionary
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Dictionary Sync Bot"
          
          # Add the file (even if it's new)
          git add formatted_dictionary.md
          
          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes to dictionary markdown"
          else
            git commit -m "Auto-update Ichrolic dictionary markdown [skip ci]"
            git push
            echo "Dictionary updated and pushed!"
          fi